apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: student-management-project
  labels:
    app: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: student-management:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/students/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/students/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
